"""Centralized prompt contracts for HERA agents."""

from prompts.device import (
	DEVICE_COMMAND_INTERPRETER_PROMPT,
	DEVICE_TARGET_CLARIFICATION_PROMPT,
)
from prompts.orchestrator import (
	DEVICE_CONTROL_RESPONSE_SYSTEM,
	FINAL_RESPONSE_SYSTEM,
	GENERAL_SYSTEM,
	PENDING_CONFIRMATION_SYSTEM,
	ROUTER_SYSTEM,
)

__all__ = [
	"DEVICE_COMMAND_INTERPRETER_PROMPT",
	"DEVICE_TARGET_CLARIFICATION_PROMPT",
	"DEVICE_CONTROL_RESPONSE_SYSTEM",
	"FINAL_RESPONSE_SYSTEM",
	"GENERAL_SYSTEM",
	"PENDING_CONFIRMATION_SYSTEM",
	"ROUTER_SYSTEM",
]
