[project]
name = "asynchronous-application-routing"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
  "ruff==0.15.11",
]

[tool.ruff]
line-length = 88
target-version = "py314"
exclude = [
  ".git",
  ".idea",
  ".pio",
  ".vscode",
  ".venv",
  "venv",
  "build",
  "dist",
  "__pycache__",
  ".ruff_cache",
  ".mypy_cache",
]

[tool.ruff.lint]
select = [
  "E",
  "W",
  "F",
  "I",
  "B",
  "UP",
  "SIM",
]
ignore = ["E501", "W191"]

[tool.ruff.format]
quote-style = "double"
indent-style = "tab"
# line-ending = "auto"
line-ending = "lf"
docstring-code-format = false
skip-magic-trailing-comma = false

[tool.mypy]
python_version = "3.14"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = false
check_untyped_defs = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_no_return = true
strict_equality = true

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["."]

[tool.coverage.run]
source = ["."]
branch = true